# Generated by Django 3.2.18 on 2023-04-26 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='remaining',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='remaining'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='spent',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='spent'),
        ),
    ]
